/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_aubry_version_console;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 *
 * @author bapti
 */
public class fenetreDeDifficulte extends javax.swing.JFrame {

    int diff;

    /**
     * Creates new form fenetreDeDifficulte
     */
    public fenetreDeDifficulte() {
        customInitComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_difficulte = new javax.swing.JPanel();
        txt_diffPartie = new javax.swing.JLabel();
        txt_bvn = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_facile = new javax.swing.JRadioButton();
        btn_normal = new javax.swing.JRadioButton();
        btn_difficile = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneau_difficulte.setBackground(new java.awt.Color(102, 102, 102));
        panneau_difficulte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_diffPartie.setText("Choix de la difficulté");
        panneau_difficulte.add(txt_diffPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, 20));

        txt_bvn.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        txt_bvn.setText("Bienvenue dans LIGHTOFF !");
        panneau_difficulte.add(txt_bvn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btn_start.setText("Démarrer la Partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_difficulte.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        btn_facile.setText("Facile");
        btn_facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facileActionPerformed(evt);
            }
        });
        panneau_difficulte.add(btn_facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        btn_normal.setText("Normale");
        btn_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalActionPerformed(evt);
            }
        });
        panneau_difficulte.add(btn_normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        btn_difficile.setText("Difficile");
        btn_difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_difficileActionPerformed(evt);
            }
        });
        panneau_difficulte.add(btn_difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneau_difficulte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneau_difficulte, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        fenetreDeJeu window = new fenetreDeJeu(diff);
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facileActionPerformed
        btn_difficile.setSelected(false);
        btn_normal.setSelected(false);
        btn_start.setEnabled(btn_facile.isSelected() || btn_normal.isSelected() || btn_difficile.isSelected());
        diff = 1;
    }//GEN-LAST:event_btn_facileActionPerformed

    private void btn_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalActionPerformed
        btn_difficile.setSelected(false);
        btn_facile.setSelected(false);
        btn_start.setEnabled(btn_facile.isSelected() || btn_normal.isSelected() || btn_difficile.isSelected());
        diff = 2;
    }//GEN-LAST:event_btn_normalActionPerformed

    private void btn_difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_difficileActionPerformed
        btn_facile.setSelected(false);
        btn_normal.setSelected(false);
        btn_start.setEnabled(btn_facile.isSelected() || btn_normal.isSelected() || btn_difficile.isSelected());
        diff = 3;
    }//GEN-LAST:event_btn_difficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeDifficulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeDifficulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeDifficulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeDifficulte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            fenetreDeDifficulte fenetre = new fenetreDeDifficulte();
            fenetre.setExtendedState(JFrame.MAXIMIZED_BOTH); // Ouvrir en plein écran
            fenetre.setVisible(true);
        });
    }

    private void customInitComponents() {
        panneau_difficulte = new javax.swing.JPanel();
        txt_diffPartie = new javax.swing.JLabel();
        txt_bvn = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        btn_facile = new javax.swing.JRadioButton();
        btn_normal = new javax.swing.JRadioButton();
        btn_difficile = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panneau_difficulte.setBackground(new java.awt.Color(102, 102, 102));
        panneau_difficulte.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new java.awt.Insets(10, 10, 10, 10);

        // Centrer le label "Bienvenue dans LIGHTOFF !"
        txt_bvn.setFont(new java.awt.Font("Segoe UI Black", 0, 50));
        txt_bvn.setText("Bienvenue dans LIGHTOFF!");
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        panneau_difficulte.add(txt_bvn, gbc);

        // Centrer le label "Choix de la difficulté"
        txt_diffPartie.setFont(new java.awt.Font("Segoe UI Black", 0, 30));
        txt_diffPartie.setText("Choix de la difficulté");
        gbc.gridy = 1;
        panneau_difficulte.add(txt_diffPartie, gbc);

        // Centrer le bouton radio "Facile"
        btn_facile.setText("Facile");
        btn_facile.addActionListener(this::btn_facileActionPerformed);
        gbc.gridy = 2;
        panneau_difficulte.add(btn_facile, gbc);

        // Centrer le bouton radio "Moyen"
        btn_normal.setText("Moyen");
        btn_normal.addActionListener(this::btn_normalActionPerformed);
        gbc.gridy = 3;
        panneau_difficulte.add(btn_normal, gbc);

        // Centrer le bouton radio "Difficile"
        btn_difficile.setText("Difficile");
        btn_difficile.addActionListener(this::btn_difficileActionPerformed);
        gbc.gridy = 4;
        panneau_difficulte.add(btn_difficile, gbc);

        // Centrer le bouton "Démarrer la Partie" en dessous des boutons radios
        btn_start.setText("Démarrer la Partie");
        btn_start.addActionListener(this::btn_startActionPerformed);
        gbc.gridy = 5;
        panneau_difficulte.add(btn_start, gbc);

        setContentPane(panneau_difficulte);

        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_difficile;
    private javax.swing.JRadioButton btn_facile;
    private javax.swing.JRadioButton btn_normal;
    private javax.swing.JButton btn_start;
    private javax.swing.JPanel panneau_difficulte;
    private javax.swing.JLabel txt_bvn;
    private javax.swing.JLabel txt_diffPartie;
    // End of variables declaration//GEN-END:variables
}
