/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_aubry_version_console;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;

/**
 *
 * @author bapti
 */
public class FenetreFinDePartie extends javax.swing.JFrame {

    static boolean win;
    static int nbCoups;

    /**
     * Creates new form FenetreFinDePartie
     *
     * @param win
     * @param nbCoupsUtilises
     */
    public FenetreFinDePartie(boolean win, int nbCoupsUtilises) {
        FenetreFinDePartie.win = win;
        nbCoups = nbCoupsUtilises;
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_msg_fin_de_partie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("GAME OVER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 20, -1, 58));

        lbl_msg_fin_de_partie.setText("Message ");
        jPanel1.add(lbl_msg_fin_de_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 96, 250, 121));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreFinDePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreFinDePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreFinDePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreFinDePartie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FenetreFinDePartie(win, nbCoups).setVisible(true);
        });
    }

    private void customInitComponents() {
        initComponents();

        if (win) {
            lbl_msg_fin_de_partie.setText("Félicitation vous avez gagné en " + nbCoups + " coups !");
            jPanel1.setBackground(Color.GREEN);
        } else {
            lbl_msg_fin_de_partie.setText("Vous avez perdu, réessayez !");
            jPanel1.setBackground(Color.RED);
        }

        jLabel1.setFont(new Font(jLabel1.getFont().getName(), jLabel1.getFont().getStyle(), 60));

        lbl_msg_fin_de_partie.setFont(new Font(lbl_msg_fin_de_partie.getFont().getName(), lbl_msg_fin_de_partie.getFont().getStyle(), 50));
        // Utiliser GridBagLayout pour centrer les composants
        jPanel1.setLayout(new GridBagLayout());

        // Contraintes pour le label "GAME OVER"
        GridBagConstraints gbcGameOver = new GridBagConstraints();
        gbcGameOver.gridx = 0;
        gbcGameOver.gridy = 0;
        gbcGameOver.weightx = 1.0;
        gbcGameOver.weighty = 0.5; // Vous pouvez ajuster le poids selon vos besoins
        gbcGameOver.anchor = GridBagConstraints.CENTER;
        jPanel1.add(jLabel1, gbcGameOver);

        // Contraintes pour le label du message
        GridBagConstraints gbcMessage = new GridBagConstraints();
        gbcMessage.gridx = 0;
        gbcMessage.gridy = 1;
        gbcMessage.weightx = 1.0;
        gbcMessage.weighty = 0.5; // Vous pouvez ajuster le poids selon vos besoins
        gbcMessage.anchor = GridBagConstraints.CENTER;
        jPanel1.add(lbl_msg_fin_de_partie, gbcMessage);

        // Maximiser la fenêtre en plein écran
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_msg_fin_de_partie;
    // End of variables declaration//GEN-END:variables
}
